"""add stored images to articles and cartes

Revision ID: 2975f1ba6d4f
Revises: c1b2a3d4e5f6
Create Date: 2026-01-12 16:13:26.841171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '2975f1ba6d4f'
down_revision: Union[str, None] = 'c1b2a3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tip: if you add NOT NULL / UNIQUE constraints, backfill existing NULL/duplicates first:
    # conn = op.get_bind()
    # conn.execute(text("UPDATE ... WHERE ..."))
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('articles', sa.Column('image_mime', sa.String(length=100), nullable=True))
    op.add_column('cartes', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('cartes', sa.Column('image_mime', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartes', 'image_mime')
    op.drop_column('cartes', 'image_data')
    op.drop_column('articles', 'image_mime')
    op.drop_column('articles', 'image_data')
    # ### end Alembic commands ###
