"""New changes

Revision ID: 636d5676e767
Revises: e510f7641dc1
Create Date: 2026-01-05 23:39:35.482148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '636d5676e767'
down_revision: Union[str, None] = 'e510f7641dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tip: if you add NOT NULL / UNIQUE constraints, backfill existing NULL/duplicates first:
    # conn = op.get_bind()
    # conn.execute(text("UPDATE ... WHERE ..."))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
