"""New changes

Revision ID: a6d2e5b51393
Revises: e3ca220b7945
Create Date: 2026-01-05 22:27:14.817529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'a6d2e5b51393'
down_revision: Union[str, None] = 'e3ca220b7945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tip: if you add NOT NULL / UNIQUE constraints, backfill existing NULL/duplicates first:
    # conn = op.get_bind()
    # conn.execute(text("UPDATE ... WHERE ..."))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
