"""New changes

Revision ID: d0b32c06d2b8
Revises: f050446ac691
Create Date: 2026-01-05 21:52:54.771250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b32c06d2b8'
down_revision: Union[str, None] = 'f050446ac691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'titre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('dictionnaire', 'mots_francais',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('histoires', 'titre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('histoires', 'typologie',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('histoires', 'periode',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('histoires', 'periode',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('histoires', 'typologie',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('histoires', 'titre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('dictionnaire', 'mots_francais',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('articles', 'titre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
