"""Initial tables

Revision ID: db47d488850f
Revises: 
Create Date: 2025-11-28 12:29:39.811091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db47d488850f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('dictionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mots_francais', sa.String(length=200), nullable=True),
    sa.Column('synonymes_francais', sa.String(length=200), nullable=True),
    sa.Column('mots_provencal', sa.String(length=200), nullable=True),
    sa.Column('eg_provencal', sa.String(length=200), nullable=True),
    sa.Column('d_provencal', sa.String(length=200), nullable=True),
    sa.Column('a_provencal', sa.String(length=200), nullable=True),
    sa.Column('h_provencal', sa.String(length=200), nullable=True),
    sa.Column('av_provencal', sa.String(length=200), nullable=True),
    sa.Column('p_provencal', sa.String(length=200), nullable=True),
    sa.Column('x_provencal', sa.String(length=200), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionnaire_id'), 'dictionnaire', ['id'], unique=False)
    op.create_table('histoires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=True),
    sa.Column('typologie', sa.String(length=30), nullable=True),
    sa.Column('periode', sa.String(length=30), nullable=True),
    sa.Column('description_courte', sa.String(length=100), nullable=True),
    sa.Column('description_longue', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histoires_id'), 'histoires', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_histoires_id'), table_name='histoires')
    op.drop_table('histoires')
    op.drop_index(op.f('ix_dictionnaire_id'), table_name='dictionnaire')
    op.drop_table('dictionnaire')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
