"""New changes

Revision ID: e3ca220b7945
Revises: 0d8bf8d5894b
Create Date: 2026-01-05 22:26:53.436307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'e3ca220b7945'
down_revision: Union[str, None] = '0d8bf8d5894b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tip: if you add NOT NULL / UNIQUE constraints, backfill existing NULL/duplicates first:
    # conn = op.get_bind()
    # conn.execute(text("UPDATE ... WHERE ..."))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
